version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: basketlytics-backend
    ports:
      - "5000:8080"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    environment:
      - FLASK_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: basketlytics-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
